title: Aditya A Prasad # your name (or website title) here
logo: "/images/whatsapp.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm currently doing my PhD at the Computational Data Science department (formerly Supercomputer Education and Research Centre) Indian Institute of Science. Working under professor Soumyendu Raha in the Scientific Computation Lab.
  <br><br>
  I am interested in using Complex Networks to model systems like the micro grid and how its stability and control can be studied using dynamical systems and differential equations.
  <br><br>
  <a href="https://www.linkedin.com/in/adityaarpithaprasad/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
